### ISSUE TITLE
Add background jobs

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1167] opened 2023-06-22 14:50 UTC
## Summary

A framework for running jobs in the background.

Some jobs we need:

- Clean up dropped tables. When dropping tables, it should be sufficient to just drop the table in the catalog, then submit a background job to actually delete from object storage.
- Compute table size. Similar to above. When a user inserts into a table, we should compute the table size following the insert. We may also want to try to "batch" these jobs to avoid a bunch of wasted work for tables that are frequently inserted into.
- Optimize table storage. Vacuum and repartition tables after some time.

Some design work may need to be done beforehand.

**Comment by greyscaled** [comment] 2023-06-26 14:59
relates to #1155 I'd assume

**Comment by greyscaled** [comment] 2023-07-12 16:34
Bumpted to high priority, since we're adjusting plans on Cloud and this facilitates storage tracking

**Comment by greyscaled** [comment] 2023-07-17 15:20
@universalmind303 - may have an idea to inherit from Actor model (link?)

Note: We do want glaredb to have control here (instead of Cloud)

**Comment by vrongmeal** [comment] 2023-07-18 08:51
We need a framework to run some jobs in the background. We can simply spawn a `tokio` thread but we need a few more features:

* Batch jobs: to run after some time only once.
* Stop the server from closing if a jobs are running.

### “Batching” jobs

**Do all compute servers run the jobs?** We do batch jobs per server, i.e., run a job once after a period of time since they might run frequently. But in a scenario, two people working on the same deployment but using different compute engines, the jobs would conflict. The issue is storage calculations might be in-accurate. The correct storage calculation might be over-written by the in-correct one. We might need to batch jobs at `metastore` level.

How this would work is, (batched) jobs are registered with `metastore`. Consider the `struct`:

```rust
pub struct JobEntry {
    pub name: String,
    pub created_at: DateTime,
    pub started: bool,
    pub options: JobOptions,
}
```

`name` is a unique identifier to refer to the job. Each job when registered will be “batched” with a previously existing job (if there was one). Once the job is started on a compute engine, the `started` parameter will be set to `true`. This should maintain the “transactional” nature of the jobs (to some extent), until we figure out how to add transactions to catalog mutations.

### Initial Implementation

A relatively simple implementation where jobs are isolated on the compute-engine level. Jobs are registered in-memory (we can extend this to persist the jobs that were registered on the server in case the server dies). A new job is created and “batched” if requested on the same server. If the job is not “batched”, it runs immediately (for eg: dropping a table).
This implementation requires that we handle a few errors loosely, because there might be a case where multiple servers try to run the same job (which could result in errors on some of the servers).

---

I gave some thought about the Actor Model. Our jobs are pretty simple. “Actors” don’t require any messaging among themselves. One could say batching of jobs require messaging but the `name` simply acts as an address for the actor and the control we require is pre-defined. Maybe someday we do find ourselves in a need for such model, but we can definitely scrape out current implementation easily.

**Comment by scsmithr** [comment] 2023-07-18 13:07
> Do all compute servers run the jobs? We do batch jobs per server, i.e., run a job once after a period of time since they might run frequently. But in a scenario, two people working on the same deployment but using different compute engines, the jobs would conflict. The issue is storage calculations might be in-accurate. The correct storage calculation might be over-written by the in-correct one. We might need to batch jobs at metastore level.

An alternative might be to store job entries in a system table backed by a delta table. Delta tables are transactional, which (should) allow us to ensure only one compute engine is running a job. However, this would require that we support `UPDATE` for those tables, and I'm not sure how much effort that would be, and if we'd need to add some stuff to delta-rs.

**Comment by vrongmeal** [comment] 2023-07-18 13:48
Using delta tables is actually a pretty neat idea. I guess we can evaluate this in some time when we reach at the stage of implementing it (maybe delta catches up till then).

**Closed** 2023-07-21 14:58 UTC
Labels: feat :sparkler:, priority-high :mountain:, sprint :runner:
