### ISSUE TITLE
Better error message when wrong glaredb command

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#2102] opened 2023-11-15 08:49 UTC
## Description

Since `glaredb` defaults to `local` command, running a command that doesn't exist (maybe because of a typo) returns a bad error message:

```
❯ ./glaredb version
Error: No such file or directory (os error 2)
```

This is because it's trying to read a file called `version` since there's no subcommand called `version`.

I would expect an error message explaining that the command `version` or an SQL file called `version` (both) do not exist.

**Comment by universalmind303** [comment] 2023-11-15 16:02
duplicate of #2101

**Closed** 2023-11-16 16:22 UTC
Labels: ux :gem:
